version: "3.8"

services:

  profile_service:
    image: profile_service
    container_name: profile_service
    build:
      context: .
      dockerfile: ./profile-service/Dockerfile
    restart: always
    ports:
      - ${PROFILE_SERVICE_PORT}:${PROFILE_SERVICE_PORT}
    environment:
      PORT: ${PROFILE_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      NATS_SUBJECT: ${NATS_SUBJECT}
    depends_on:
      - nats
    networks:
      - network

  follow_service:
    image: follow_service
    container_name: follow_service
    build:
      context: .
      dockerfile: ./follow-service/Dockerfile
    restart: always
    ports:
      - ${FOLLOW_SERVICE_PORT}:${FOLLOW_SERVICE_PORT}
    environment:
      PORT: ${FOLLOW_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      NATS_SUBJECT: ${NATS_SUBJECT}
    depends_on:
      - nats
    networks:
      - network

  nats:
    image: nats
    container_name: nats
    restart: on-failure
    networks:
      - network

networks:
  network:
    driver: bridge