CREATE TABLE dbo.Addresses (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Street VARCHAR(50),
	StreetNumber VARCHAR(10),
	City VARCHAR(50),
	Country VARCHAR (50), 
	IsDeleted BIT NOT NULL
)

CREATE TABLE dbo.Users
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Jmbg VARCHAR(13) UNIQUE NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Gender VARCHAR(10) NOT NULL,
	UserType VARCHAR(10) NOT NULL,
	IsActive BIT NOT NULL,
	AddressId INT,
	CONSTRAINT FK_ADDRESSES_PROFESSORS
	FOREIGN KEY (AddressId) REFERENCES dbo.Addresses (Id)
)

CREATE TABLE dbo.Professors
(
 Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 UserId INT NOT NULL UNIQUE,
 CONSTRAINT FK_USERS_PROFESSORS
 FOREIGN KEY (UserId) REFERENCES dbo.Users (Id)
)
