version: "3.1"

services:
  # Our service.
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "library-server"
    hostname: "library-server"
    #Mapping ports
    ports:
      # <port_on_local>:<port_in_machine>
      - 8080:8080
    #Will be accessible through os.Getenv("PORT")
    environment:
      - PORT=8080
      # NoSQL: environment variable holding connection URI for Cockroach database
      # We use the postgresql protocol to connect to it because Cockroach is wire compatible with it
      - COCKROACH_DB=postgresql://root@cockroach:26257/defaultdb?sslmode=disable
    depends_on:
      cockroach:
        condition: service_healthy

  # NoSQL: CockroachDB
  cockroach:
    image: cockroachdb/cockroach:v23.1.11
    # command: start-single-node --advertise-addr 'localhost' --insecure
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - cockroach_store:/cockroach/cockroach-data

volumes:
  cockroach_store:
