using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using System.ComponentModel;
using System.Data;

namespace ADOWPfTest2
{
    /// <summary>
    /// Interaction logic for FakultetiWindow.xaml
    /// </summary>
    public partial class FakultetiWindow : Window
    {
        ICollectionView view;

        public FakultetiWindow()
        {
            InitializeComponent();
            
            view = CollectionViewSource.GetDefaultView(Aplikacija.Instance.Fakulteti);
            dgFakulteti.ItemsSource = view;
            dgFakulteti.IsSynchronizedWithCurrentItem = true;
        }

        private void btnSave_Click(object sender, RoutedEventArgs e)
        {
            this.DialogResult = true;
            Aplikacija.Instance.SnimiFakultete();
        }

        private void dgFakulteti_AutoGeneratedColumns(object sender, EventArgs e)
        {
            //sakriven id i stanje
            dgFakulteti.Columns[0].Visibility = System.Windows.Visibility.Hidden;
            dgFakulteti.Columns[3].Visibility = System.Windows.Visibility.Hidden;
        }

        private void btnDelete_Click(object sender, RoutedEventArgs e)
        {
            Fakultet selectedFakultet = view.CurrentItem as Fakultet;
            Aplikacija.Instance.Fakulteti.Remove(selectedFakultet);
        }
    }
}
