using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using System.ComponentModel;
using System.Data;

namespace LINQWpfTest
{
    /// <summary>
    /// Interaction logic for FakultetiWindow.xaml
    /// </summary>
    public partial class FakultetiWindow : Window
    {
        ICollectionView view;

        public FakultetiWindow()
        {
            InitializeComponent();
            createView();                     
        }

        private void createView()
        {
            view = CollectionViewSource.GetDefaultView(
                Aplikacija.Instance.Fakulteti.ToList<Fakultet>());
            dgFakulteti.ItemsSource = view;
            dgFakulteti.IsSynchronizedWithCurrentItem = true;  
        }

        private void dgFakulteti_AutoGeneratedColumns(object sender, EventArgs e)
        {
            //sakriven id
            dgFakulteti.Columns[0].Visibility = System.Windows.Visibility.Hidden;
        }

        private void btnDelete_Click(object sender, RoutedEventArgs e)
        {
            Fakultet selektovaniFakultet = view.CurrentItem as Fakultet;
            if (selektovaniFakultet != null)
            {
                Aplikacija.Instance.Fakulteti.DeleteOnSubmit(selektovaniFakultet);
                Aplikacija.Instance.SnimiFakultete();
                createView();
            }
        }

        private void btnClose_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }

        private void btnAdd_Click(object sender, RoutedEventArgs e)
        {
            Fakultet noviFakultet = new Fakultet();
            FakultetEditWindow few = new FakultetEditWindow(noviFakultet);
            if (few.ShowDialog() == true)
            {
                createView();//osvezavanje prikaza
            }
        }

        private void btnUpdate_Click(object sender, RoutedEventArgs e)
        {
            Fakultet selektovaniFakultet = view.CurrentItem as Fakultet; //preuzimanje selektovanog fakulteta
            
            if (selektovaniFakultet != null)//ako je neki fakultet selektovan
            {
                FakultetEditWindow few = new FakultetEditWindow(selektovaniFakultet);
                if (few.ShowDialog() != true) //ako je kliknuo cancel, ponistavaju se izmene nad objektom
                    Aplikacija.Instance.PonistiIzmene(selektovaniFakultet);

                createView(); //osvezavanje prikaza u gridu                
            }
        }
    }
}
