basePath: /
info:
    description: 'Title: Post API'
    title: Post API
    version: 0.0.1
paths:
    /post/:
        post:
            description: Add new post
            operationId: createPost
            parameters:
                - description: 'name: body'
                  in: body
                  name: body
                  required: true
                  schema: {}
                  x-go-name: Body
            responses:
                "201":
                    $ref: '#/responses/ResponsePost'
                "400":
                    $ref: '#/responses/ErrorResponse'
                "415":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
    /post/{id}/:
        delete:
            description: Delete post
            operationId: deletePost
            parameters:
                - description: Post ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "204":
                    $ref: '#/responses/NoContentResponse'
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
        get:
            description: Get post by ID
            operationId: getPostById
            parameters:
                - description: Post ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "200":
                    $ref: '#/responses/ResponsePost'
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
    /posts/:
        get:
            description: Get all posts
            operationId: getPosts
            responses:
                "200":
                    $ref: '#/responses/ResponsePost'
            tags:
                - post
produces:
    - application/json
responses:
    ErrorResponse:
        description: ""
        headers:
            message:
                description: |-
                    Message of the error
                    in: string
                type: string
            status:
                description: |-
                    Error status code
                    in: int64
                format: int64
                type: integer
    NoContentResponse:
        description: ""
    ResponsePost:
        description: ""
        headers:
            id:
                description: |-
                    Id of the post
                    in: string
                type: string
            tags:
                description: |-
                    List of tags of the post
                    in: []string
                items:
                    type: string
                type: array
            text:
                description: |-
                    Text content of the post
                    in: string
                type: string
            title:
                description: |-
                    Title of the post
                    in: string
                type: string
schemes:
    - http
swagger: "2.0"
