using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using System.ComponentModel;
using System.Data;

namespace ADOWPfTest
{
    /// <summary>
    /// Interaction logic for FakultetiWindow.xaml
    /// </summary>
    public partial class FakultetiWindow : Window
    {
        public FakultetiWindow()
        {
            InitializeComponent();
            
            ICollectionView view = CollectionViewSource.GetDefaultView(
                Aplikacija.Instance.Ds.Tables["Fakultet"]);
            dgFakulteti.ItemsSource = view;
            dgFakulteti.IsSynchronizedWithCurrentItem = true;
        }

        private void btnSave_Click(object sender, RoutedEventArgs e)
        {
            Aplikacija.Instance.SnimiFakultete();
            this.DialogResult = true;
            this.Close();
        }

        private void dgFakulteti_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgFakulteti.Columns[0].Visibility = System.Windows.Visibility.Hidden;//prva kolona je ID, ne treba da se prikazuje korisniku
        }

        private void btnDelete_Click(object sender, RoutedEventArgs e)
        {
            DataRowView selectedRow = dgFakulteti.SelectedItem as DataRowView;
            if (selectedRow != null)
                selectedRow.Delete();
        }
    }
}
